#!/bin/bash
# By: Nathan Peralta
# Last modified: 2023-Mar-28 23:04

source Universaltemplates 

CSSheader(){
	filename=$1
	creators=$2	
	echo "/*=====" >> $filename
	echo "$filename" >> $filename

	creator_name $filename $creators

	dateCreated $filename
	echo "=====*/" >> $filename
	insertHtml $filename	
}


insertHtml(){
	filename=$1
	read -p "Which html file do you want? " htmlFile

	var=$(find ~/public_html -name "$htmlFile")

	fileLoc=$(find ~/public_html -name "$filename")
	fileLink="		<link href=\"https://nrs-projects.humboldt.edu/~np157$fileLoc\" type=\"text/css\" rel=\"stylesheet\" />"	
	fileLink="		<link href=\"$fileLoc\" type=\"text/css\" rel=\"stylesheet\" />"	

	#insertElements $filename $var

	
	htmlClass=($(grep -ho 'class=".*"' $var))

	unset dupes
	declare -A dupes
	for element in "${htmlClass[@]}"
	do
		if [ -z ${dupes[$element]} ]
		then
			NEWARRAY+=("$element")
		fi
		dupes["$element"]=1
	done

	for htmlCl in "${NEWARRAY[@]}"
	do
		echo "${htmlCl}" >> $filename
		
	done	
	
	sed -i "/link/ a $fileLink" $var	
	sed -i 's/^class=\"/./g' $filename	
	sed -i 's/\"/\n{ \n \n}/g' $filename
	sed -i '/<\/.*>/d' $filename
	sed -i 's/>/\n{ \n \n}/g' $filename
	sed -i 's/<//g' $filename
	
}

insertElements(){
	filename=$1
	var=$2
	toRemove="[<>]"
	htmlEl=($(grep -ho '<.*>' $var | grep -v 'html'))
	unset dupeARRAY
	unset dupes
	declare -A dupes
	for element in "${htmlEl[@]}"
	do
		new=${element//$toRemove/}
		echo "$new"
		if [ -z ${dupes[$new]} ]
		then
			dupeARRAY+=("$new")
		fi
		dupes["$new"]=1
	done
	
	for htmlCl in "${dupeARRAY[@]}"
	do
		echo "${htmlCl}" >> $filename
	done	
}
