#!/bin/bash
# By: Nathan Peralta
# Last modified: 2023-Mar-09 12:47

source Universaltemplates 

CSSheader(){
	filename=$1
	creators=$2	
	echo "/*=====" >> $filename
	echo "$filename" >> $filename

	creator_name $filename $creators

	lastModified=$(date +"%Y-%b-%d")
	echo "Last modified: $lastModified" >> $filename
	echo "=====*/" >> $filename
	insertHtml $filename	
}


insertHtml(){
	filename=$1
	read -p "Which html file do you want? " htmlFile
	var=$(find ~ -name "$htmlFile")
	#fileLoc=$(find ~ -name "$filename")
	#fileLink="		<link href=\"https://nrs-projects.humboldt.edu/~np157$fileLoc\" type=\"text/css\" rel=\"stylesheet\" />"	
	fileLink="		<link href=\"$filename\" type=\"text/css\" rel=\"stylesheet\" />"	

	sed -i "/link/ a $fileLink" $var	
}
