#!/bin/bash
# Last Modified: 2023-02-01

source Universaltemplates

HTMLheader(){
	filename=$1
	creator=$2
	echo "<!DOCTYPE html>" >> $filename
	echo '<html lang="en" xmlns="https://www.w3.org/1999/xhtml">' >> $filename
	echo "<!--" >> $filename
	read -p "Enter your names " names
	echo "	By: $names" >> $filename
	
	newModified=$(date +"%Y-%b-%d %R")
	modifiedForm="Last modified: $newModified"
	
	echo "	$modifiedForm" >> $filename

	HTMLpath $filename

	echo "-->" >> $filename
	echo "	<head>" >> $filename
	echo "	<title> INSERT_TITLE </title>" >> $filename
	echo "		<meta charset=\"UTF-8\">" >> $filename
	echo "		<link href=\"http://nrs-projects.humboldt.edu/~st10/styles/normalize.css\" type=\"text/css\" rel=\"stylesheet\" />" >> $filename
	echo "	</head>" >> $filename
	echo >> $filename
	echo "</html>" >> $filename
}

HTMLpath(){
	filename=$1	
	echo "   you can run this using this URL: ">> $filename
	fileLoc=$(find ~ -name "$filename")
	pageLink="https://nrs-projects.humboldt.edu/~np157$fileLoc"
	echo "   $pageLink" >> $filename
	sed -i 's/\/home.*\/np157//' $filename
	
}

PHPheader(){
	filename=$1
	creators=$2
	echo "/*=====" >> $filename
	echo "	$filename" >> $filename
	creator_name $filename $creators
	dateCreated $filename
	echo "=====*/" >> $filename

	echo -e "<?php \n" >> $filename
	
	echo "?>" >> $filename	
}
