#!/bin/bash
# Autoformat for 328
# Nathan Peralta
# Last modified: 2023-Mar-22 17:28

source SQLfunctions
source HTMLfunctions
source CSStemplate
source templateFunct

if [ $# -eq 0 ]
then
	echo "Add file name: "
	read filename
else
	filename=$1
fi

if [ -e $filename ]
then
	case $filename in
		*.css)
			inFile=$(grep -rl --include \*.html "$filename" ~/)
			compFile=$(find ~ -name  "$filename")
			currLink=$(grep -o "/home.*/$filename"  $inFile) 
		
			if [[ "$currLink" == "$compFile"* ]]
			then
				echo "true"
			else
				echo "$compFile is not  $currLink"
			fi
	esac

	newModified=$(date +"%Y-%b-%d %R")
	modifiedForm="Last modified: $newModified"
	sed -i "1,5 s/[Ll]ast modified: .*/$modifiedForm/g" $filename

elif [ ! -f $filename ]
then
	case $filename in
		*.sh)
			linuxTemplate $filename $2
			read -p "What permissions will you give it? " permission
			chmod $permission $filename
			;;
		*.sql)
			PLtemplate $filename $2
			read -p "What permissions will you give it? " permission
			chmod $permission $filename
			;;
		*.html)
			HTMLheader $filename $2
			chmod 644 $filename
			;;
		*.php)
			PHPheader $filename $2
			chmod 644 $filename
		*.css)
			CSSheader $filename $2
			chmod 644 $filename
			;;
		*)
			echo "Which template do you need? Type 0 for options?"
			read -rp "Template Choice: " temp_choice
			main_menu $filename $temp_choice $2
			read -p "What permissions will you give it? " permission
			chmod $permission $filename
			;;
	esac

fi

nano $filename
