#!/bin/bash
# Autoformat for 328
# Nathan Peralta
# Last Modified: 2023-Jan-27
#		2023-Feb-01
source SQLfunctions
source HTMLfunctions
source templateFunct

if [ $# -eq 0 ]
then
	echo "Add file name: "
	read filename
else
	filename=$1
fi

if [ -e $filename ]
then
	echo "Exists"

	newModified=$(date +"%Y-%b-%d %R")
	modifiedForm="Last modified: $newModified"
	sed -i "s/Last modified: .*/$modifiedForm/g" $filename

elif [ ! -f $filename ]
then
	echo "Which template do you need? Type 0 for options?"
	read -rp "Template Choice: " temp_choice
	main_menu $filename $temp_choice $2
	read -p "What permissions will you give it? " permission
	chmod $permission $filename

fi

nano $filename
