#!/bin/bash
# Last modified: 2023-Mar-08 18:16

source SQLfunctions
source HTMLfunctions
source CSStemplate
source Universaltemplates
main_menu(){
	filename=$1
	answer=$2
	creators=$3
	echo $answer
	if [ $answer = 0 ]
	then
		echo "1. Linux 2. PL/SQL 3. HTML"
		echo "4. CSS"
		read -p "Template Choice: " answers
		main_menu $filename $answers $creators
	elif [ $answer = 1 ]
	then
		linuxTemplate $filename $creators
	elif [ $answer = 2 ]
	then
		PLtemplate $filename $creators 
	elif [ $answer = 3 ]
	then
		HTMLheader $filename
	elif [ $answer = 4 ]
	then
		CSSheader $filename $creators
	else
		echo "Not an option, please try again or type 0 for the options"
		read -rp "Template Choice: " answers
		main_menu $filename $answers $creators
	fi
}


checkOption(){
	choice=$1
	PLoptions='[1234]'
	if ! [[ $choice =~ $PLoptions ]]
	then 
		echo "Not an option"
		read -p "Please choice a number between 1-4: " choiceTwo
		checkOption $choiceTwo
	fi
}

linuxTemplate(){
	filename=$1

	echo "#!/bin/bash" >> $filename
	creator_name $filename $2 "Linux"

	lastModified=$(date +"%Y-%b-%d %R")
        echo "# Last modified: $lastModified" >> $filename

}

PLtemplate(){
	filename=$1
	echo "/*===" >> $filename
        echo "$filename" >> $filename

        creator_name $filename $2
	
	lastModified=$(date +"%Y-%b-%d %R")
        echo "Last modified: $lastModified" >> $filename
       
	echo "===*/" >> $filename
        echo "What do you want to make?"
        echo "1) A procedure"
        echo "2) A function"
        echo "3) A trigger"
        echo "4) All of the above"
        read -p "Things to add: " template_choice

        checkOption $template_choice

        if [ $template_choice == 4 ]
        then
                howMany_sql 1 $filename
                howMany_sql 2 $filename
                howMany_sql 3 $filename
        else
                howMany_sql $template_choice $filename
        fi

	echo "set serveroutput on" >> $filename
        	for prodStr in ${prodArray[@]}
        	do
          		testingCreation $filename $prodStr
                	testingCreation $filename $prodStr
        	done

		for functStr in ${functArray[@]}
        	do
          		testingCreation $filename $functStr
                	testingCreation $filename $functStr
        	done

		for trigStr in ${trigArray[@]}
        	do
          		testingCreation $filename $trigStr
        	done
}
