#!/bin/bash
# Created By: Nathan Peralta
# Last modified: 2023-Mar-27 17:15

# add the creator's name

creator_name(){
	filename=$1
	if  [ -z $2 ]
	then
		read -p "Enter your name: " creators
		echo "Created by: $creators" >> $filename
	elif [ "$2" == "Linux" ]
	then
		read -p "Enter your name: " creators
		echo "# Created by: $creators" >> $filename
	else
		creators=$2
		if [ "$3" == "Linux" ]
		then 
			echo "# Created by: $creators" >> $filename
		else
			echo "Created by: $creators" >> $filename
		fi
	fi
}

dateCreated(){
	filename=$1

	newModified=$(date +"%Y-%b-%d %R")
	modifiedForm="Last modified: $newModified"
	
	echo "	$modifiedForm" >> $filename
}

numCheck(){
        if [[ ! $multipleFiles =~ [0-9] ]]
        then
            	echo "Not a number"
                read -p "Please enter a number: " multipleFiles
                numCheck $multipleFiles
        fi
}

